operators-installer:
  operatorGroups:
    - name: openshift-gitops
      createNamespace: true
      targetOwnNamespace: false
  operators:
    - channel: latest
      installPlanApproval: Manual
      name: openshift-gitops-operator
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: openshift-gitops-operator.v1.18.1
      namespace: openshift-gitops
      installPlanVerifierActiveDeadlineSeconds: 1200